# Generated by Django 4.2.30 on 2026-08-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microphonecommand',
            name='executed',
        ),
        migrations.AddField(
            model_name='microphonecommand',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microphonecommand',
            name='result',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='microphonecommand',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='microphonecommand',
            name='command',
            field=models.CharField(max_length=20),
        ),
    ]
